"""posts table

Revision ID: 5be991c1b741
Revises: f6d38d28b849
Create Date: 2020-07-21 15:19:23.546325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5be991c1b741'
down_revision = 'f6d38d28b849'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('agent_username', sa.String(length=64), nullable=True))
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.create_foreign_key(None, 'post', 'agent', ['agent_username'], ['username'])
    op.drop_column('post', 'agent_id')
    op.drop_column('post', 'img_filename')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('img_filename', sa.VARCHAR(), nullable=True))
    op.add_column('post', sa.Column('agent_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.create_foreign_key(None, 'post', 'agent', ['agent_id'], ['id'])
    op.drop_column('post', 'agent_username')
    # ### end Alembic commands ###
