"""users table

Revision ID: fd81006cfa1b
Revises: 4374cf5aacbe
Create Date: 2020-07-19 00:36:14.743257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd81006cfa1b'
down_revision = '4374cf5aacbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent', sa.Column('name', sa.String(length=100), nullable=True))
    op.add_column('agent', sa.Column('proffession', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent', 'proffession')
    op.drop_column('agent', 'name')
    # ### end Alembic commands ###
